### PR TITLE
Use GitHub Actions to auto build Docker (amd64 and arm64 multiarch) and push to GitHub Container Registry

### PR DESCRIPTION
**Pull request by rpardini**
Hi, I needed an arm64 version of the image, so I forked and implemented.
I also bumped openjdk to latest 11. That base image is already arm64 enabled.
So here's the Github Actions incantation, in case you might want it.
(It does not publish to DockerHub so I can keep it secret-free)

### CODE REVIEW

**Comment by gillg** [comment]
I wait for it too !

**Comment by rpardini** [comment]
> I wait for it too !

Try https://github.com/rpardini/cerebro-docker/pkgs/container/cerebro-docker

**Comment by applike-ss** [comment]
@lmenezes mind merging?

**Comment by moliware** [comment]
I'm merging this. Thank you!

**Comment by rpardini** [comment]
Hi @moliware thanks for the merge. I see packages are already published.
With the hardening merge later, the `FROM` for the last stage ended up with the specific jre version... can you fix or should I send another PR?

**Comment by moliware** [comment]
If you could send another PR, that would be awesome. I'll take care of it as soon as possible

**Pull request merged**
